### ISSUE TITLE
Teha tekstibaasil chat valmis

### ISSUE THREAD

**Issue by IngoIgnasov** [TheoMuffin/tetris#2]

**Comment by karlomblus** [comment]
Chati server peaks minu "mänguserveri" külge ühenduma

**Comment by IngoIgnasov** [comment]
> Chati server peaks minu "mänguserveri" külge ühenduma
Et siis kõik töötab ühe serversocketi peal? Igatahes, ma teen enne eraldi töötava valmis, hiljem saab kokku monteerida.

**Comment by karlomblus** [comment]
Ma mõtlesin, et töö jagamise mõte ongi, et üks teeb serveri ja teine klienti :)
