### ISSUE TITLE
Kliendi taas-sisselogimine

### ISSUE THREAD

**Issue by TheoMuffin** [TheoMuffin/tetris#6]
1)Login kliendist sisse
2)Panen akna kinni (login välja), ilmub sisselogimise aken taas
3)Taas sisselogimine ebaõnnestub, olenemata parooli õigsusest, sest aken läheb kinni.

Kui peale sammu (2), teen uue kliendi lahti, siis sisselogimine õnnestub.

**Comment by karlomblus** [comment]
#4
